// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: scheduler.proto

package schedulev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScheduleRequest represents a single delayed event to be scheduled.
type ScheduleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Globally unique identifier for the event.
	// Used for idempotency and deduplication.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Unix timestamp (seconds) when the event should be executed.
	// Must be strictly greater than current time.
	ExecuteAt int64 `protobuf:"varint,2,opt,name=execute_at,json=executeAt,proto3" json:"execute_at,omitempty"`
	// Opaque payload that will be published as-is
	// to downstream systems when the event fires.
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	mi := &file_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequest.ProtoReflect.Descriptor instead.
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ScheduleRequest) GetExecuteAt() int64 {
	if x != nil {
		return x.ExecuteAt
	}
	return 0
}

func (x *ScheduleRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ScheduleResponse represents the result of a Schedule request.
type ScheduleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates whether the event was successfully accepted for scheduling.
	Accepted      bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	mi := &file_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_scheduler_proto protoreflect.FileDescriptor

const file_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x0fscheduler.proto\x12\fscheduler.v1\"e\n" +
	"\x0fScheduleRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"execute_at\x18\x02 \x01(\x03R\texecuteAt\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\".\n" +
	"\x10ScheduleResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2]\n" +
	"\x10SchedulerService\x12I\n" +
	"\bSchedule\x12\x1d.scheduler.v1.ScheduleRequest\x1a\x1e.scheduler.v1.ScheduleResponseBJZHgithub.com/HariPrasath-3/scheduler-service/proto/scheduler/v1;schedulev1b\x06proto3"

var (
	file_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_proto_rawDescData []byte
)

func file_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)))
	})
	return file_scheduler_proto_rawDescData
}

var file_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_scheduler_proto_goTypes = []any{
	(*ScheduleRequest)(nil),  // 0: scheduler.v1.ScheduleRequest
	(*ScheduleResponse)(nil), // 1: scheduler.v1.ScheduleResponse
}
var file_scheduler_proto_depIdxs = []int32{
	0, // 0: scheduler.v1.SchedulerService.Schedule:input_type -> scheduler.v1.ScheduleRequest
	1, // 1: scheduler.v1.SchedulerService.Schedule:output_type -> scheduler.v1.ScheduleResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_scheduler_proto_init() }
func file_scheduler_proto_init() {
	if File_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_proto_depIdxs,
		MessageInfos:      file_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_proto = out.File
	file_scheduler_proto_goTypes = nil
	file_scheduler_proto_depIdxs = nil
}
