// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/scheduler/scheduler.proto

package schedulerv1

import (
	common "github.com/HariPrasath-3/scheduler-service/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScheduleRequest represents a single delayed event to be scheduled.
type ScheduleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the event.
	// must be uuid format.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Unix timestamp (seconds) when the event should be executed.
	// Must be strictly greater than current time.
	ExecuteAt int64 `protobuf:"varint,2,opt,name=execute_at,json=executeAt,proto3" json:"execute_at,omitempty"`
	// Opaque payload that will be published as-is
	// to downstream systems when the event fires.
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Topic to which the event will be published when it fires.
	Topic         string `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequest.ProtoReflect.Descriptor instead.
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ScheduleRequest) GetExecuteAt() int64 {
	if x != nil {
		return x.ExecuteAt
	}
	return 0
}

func (x *ScheduleRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ScheduleRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

// ScheduleResponse represents the result of a Schedule request.
type ScheduleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status of the scheduling operation.
	Status        *common.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// CancelRequest represents a request to cancel a scheduled event.
type CancelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the event to be canceled.
	EventId       string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *CancelRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// CancelResponse represents the result of a Cancel request.
type CancelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status of the cancellation operation.
	Status        *common.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *CancelResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_proto_scheduler_scheduler_proto protoreflect.FileDescriptor

const file_proto_scheduler_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/scheduler/scheduler.proto\x12\fscheduler.v1\x1a\x19proto/common/status.proto\"{\n" +
	"\x0fScheduleRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"execute_at\x18\x02 \x01(\x03R\texecuteAt\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\":\n" +
	"\x10ScheduleResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusR\x06status\"*\n" +
	"\rCancelRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"8\n" +
	"\x0eCancelResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.common.StatusR\x06status2\xa2\x01\n" +
	"\x10SchedulerService\x12I\n" +
	"\bSchedule\x12\x1d.scheduler.v1.ScheduleRequest\x1a\x1e.scheduler.v1.ScheduleResponse\x12C\n" +
	"\x06Cancel\x12\x1b.scheduler.v1.CancelRequest\x1a\x1c.scheduler.v1.CancelResponseBKZIgithub.com/HariPrasath-3/scheduler-service/proto/scheduler/v1;schedulerv1b\x06proto3"

var (
	file_proto_scheduler_scheduler_proto_rawDescOnce sync.Once
	file_proto_scheduler_scheduler_proto_rawDescData []byte
)

func file_proto_scheduler_scheduler_proto_rawDescGZIP() []byte {
	file_proto_scheduler_scheduler_proto_rawDescOnce.Do(func() {
		file_proto_scheduler_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scheduler_scheduler_proto_rawDesc), len(file_proto_scheduler_scheduler_proto_rawDesc)))
	})
	return file_proto_scheduler_scheduler_proto_rawDescData
}

var file_proto_scheduler_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_scheduler_scheduler_proto_goTypes = []any{
	(*ScheduleRequest)(nil),  // 0: scheduler.v1.ScheduleRequest
	(*ScheduleResponse)(nil), // 1: scheduler.v1.ScheduleResponse
	(*CancelRequest)(nil),    // 2: scheduler.v1.CancelRequest
	(*CancelResponse)(nil),   // 3: scheduler.v1.CancelResponse
	(*common.Status)(nil),    // 4: common.Status
}
var file_proto_scheduler_scheduler_proto_depIdxs = []int32{
	4, // 0: scheduler.v1.ScheduleResponse.status:type_name -> common.Status
	4, // 1: scheduler.v1.CancelResponse.status:type_name -> common.Status
	0, // 2: scheduler.v1.SchedulerService.Schedule:input_type -> scheduler.v1.ScheduleRequest
	2, // 3: scheduler.v1.SchedulerService.Cancel:input_type -> scheduler.v1.CancelRequest
	1, // 4: scheduler.v1.SchedulerService.Schedule:output_type -> scheduler.v1.ScheduleResponse
	3, // 5: scheduler.v1.SchedulerService.Cancel:output_type -> scheduler.v1.CancelResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_scheduler_scheduler_proto_init() }
func file_proto_scheduler_scheduler_proto_init() {
	if File_proto_scheduler_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scheduler_scheduler_proto_rawDesc), len(file_proto_scheduler_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scheduler_scheduler_proto_goTypes,
		DependencyIndexes: file_proto_scheduler_scheduler_proto_depIdxs,
		MessageInfos:      file_proto_scheduler_scheduler_proto_msgTypes,
	}.Build()
	File_proto_scheduler_scheduler_proto = out.File
	file_proto_scheduler_scheduler_proto_goTypes = nil
	file_proto_scheduler_scheduler_proto_depIdxs = nil
}
