// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/common/status.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StatusCode enumerates possible status codes for operations.
type StatusCode int32

const (
	// Operation completed successfully.
	StatusCode_SUCCESS StatusCode = 0
	// Invalid request parameters or malformed input.
	StatusCode_BAD_REQUEST StatusCode = 1
	// Resource conflict, such as duplicate entry.
	StatusCode_CONFLICT StatusCode = 2
	// Unexpected server error occurred.
	StatusCode_INTERNAL_SERVER_ERROR StatusCode = 3
	// Requested resource was not found.
	StatusCode_NOT_FOUND StatusCode = 4
	// Operation completed successfully with no content to return.
	StatusCode_NO_CONTENT StatusCode = 5
	// Record was found in the system.
	StatusCode_RECORD_FOUND StatusCode = 6
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "SUCCESS",
		1: "BAD_REQUEST",
		2: "CONFLICT",
		3: "INTERNAL_SERVER_ERROR",
		4: "NOT_FOUND",
		5: "NO_CONTENT",
		6: "RECORD_FOUND",
	}
	StatusCode_value = map[string]int32{
		"SUCCESS":               0,
		"BAD_REQUEST":           1,
		"CONFLICT":              2,
		"INTERNAL_SERVER_ERROR": 3,
		"NOT_FOUND":             4,
		"NO_CONTENT":            5,
		"RECORD_FOUND":          6,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_status_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_proto_common_status_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_status_proto_rawDescGZIP(), []int{0}
}

// Status represents the outcome of an operation.
type Status struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Code indicating the result of the operation.
	Code StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=common.StatusCode" json:"code,omitempty"`
	// Human-readable message providing additional details.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_proto_common_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_common_status_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_SUCCESS
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_common_status_proto protoreflect.FileDescriptor

const file_proto_common_status_proto_rawDesc = "" +
	"\n" +
	"\x19proto/common/status.proto\x12\x06common\"J\n" +
	"\x06Status\x12&\n" +
	"\x04code\x18\x01 \x01(\x0e2\x12.common.StatusCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x84\x01\n" +
	"\n" +
	"StatusCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x0f\n" +
	"\vBAD_REQUEST\x10\x01\x12\f\n" +
	"\bCONFLICT\x10\x02\x12\x19\n" +
	"\x15INTERNAL_SERVER_ERROR\x10\x03\x12\r\n" +
	"\tNOT_FOUND\x10\x04\x12\x0e\n" +
	"\n" +
	"NO_CONTENT\x10\x05\x12\x10\n" +
	"\fRECORD_FOUND\x10\x06B@Z>github.com/HariPrasath-3/scheduler-service/proto/common;commonb\x06proto3"

var (
	file_proto_common_status_proto_rawDescOnce sync.Once
	file_proto_common_status_proto_rawDescData []byte
)

func file_proto_common_status_proto_rawDescGZIP() []byte {
	file_proto_common_status_proto_rawDescOnce.Do(func() {
		file_proto_common_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_status_proto_rawDesc), len(file_proto_common_status_proto_rawDesc)))
	})
	return file_proto_common_status_proto_rawDescData
}

var file_proto_common_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_common_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_common_status_proto_goTypes = []any{
	(StatusCode)(0), // 0: common.StatusCode
	(*Status)(nil),  // 1: common.Status
}
var file_proto_common_status_proto_depIdxs = []int32{
	0, // 0: common.Status.code:type_name -> common.StatusCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_common_status_proto_init() }
func file_proto_common_status_proto_init() {
	if File_proto_common_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_status_proto_rawDesc), len(file_proto_common_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_status_proto_goTypes,
		DependencyIndexes: file_proto_common_status_proto_depIdxs,
		EnumInfos:         file_proto_common_status_proto_enumTypes,
		MessageInfos:      file_proto_common_status_proto_msgTypes,
	}.Build()
	File_proto_common_status_proto = out.File
	file_proto_common_status_proto_goTypes = nil
	file_proto_common_status_proto_depIdxs = nil
}
